# Generated by Django 3.0.6 on 2020-05-26 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200526_1952'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='sex_type',
        ),
    ]
