# Generated by Django 3.0.6 on 2020-06-01 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='np_department',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
