# Generated by Django 3.0.6 on 2020-06-01 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_np_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='np_department',
            field=models.IntegerField(default=0),
        ),
    ]
