# Generated by Django 3.0.6 on 2020-06-01 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200602_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='np_department',
            field=models.CharField(max_length=3),
        ),
    ]
