# Generated by Django 3.0.6 on 2020-06-02 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200602_0256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='np_department',
        ),
        migrations.AddField(
            model_name='order',
            name='postal_department',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
